/// Localization class for Parkino app
/// Supports English, French, and Arabic languages

class AppLocalizations {
  static const String _defaultLocale = 'en';
  static String _currentLocale = _defaultLocale;

  // English translations
  static const Map<String, String> _en = {
    // Common
    'app_name': 'Parkino',
    'app_title': 'Parkino',
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'create_account': 'Create an account',
    'forgot_password': 'Forgot Password?',
    'remember_me': 'Remember me',
    'password': 'Password',
    'email': 'Email Address',
    'email_hint': 'you@example.com',
    'password_hint': 'Enter your password',
    'username': 'Username',
    'phone': 'Phone Number',
    'confirm_password': 'Confirm Password',
    'create_an_account': 'Create Your Account',
    'sign_in_title': 'Welcome Back',
    'dont_have_account': "Don't have an account? ",
    'already_have_account': 'Already have an account? ',
    'home': 'Home',
    'map': 'Map',
    'stats': 'Stats',
    'notifications': 'Notifications',
    'profile': 'Profile',
    'parking_availability': 'Parking Availability',
    'current_status': 'Current Status',
    'available': 'AVAILABLE',
    'full': 'FULL',
    'occupied': 'OCCUPIED',
    'free': 'FREE',
    'peak_hours': 'Peak Hours',
    'nearest_spot': 'Nearest Spot',
    'view_parking_map': 'VIEW PARKING MAP',
    'language': 'Language',
    'english': 'English',
    'french': 'Français',
    'arabic': 'العربية',
    // User management
    'user_management': 'User Management',
    'back_to_sign_in': 'Back to Sign In',
    'go_to_home': 'Go to Home',
    'sign_out': 'Sign Out',
    'are_you_sure_sign_out': 'Are you sure you want to sign out?',
    'cancel': 'Cancel',
    'reset_password': 'Reset Password',
    'send_reset_link': 'Send Reset Link',
    'password_reset_successful': 'Password Reset Successful!',
    'welcome_to_parkino': 'Welcome to Parkino',
    'sign_in_successful': 'Sign in successful!',
    'sign_in_failed': 'Sign in failed',
    'create_account_button': 'Create an account',
    'go_to_sign_in': 'Go to Sign In',
    'edit_profile': 'Edit Profile',
    'close': 'Close',
    'coming_soon': 'Coming soon',
    // Home Screen
    'smart_parking': 'Smart Parking',
    'parking_status': 'Parking Status',
    'fully_occupied': 'FULLY OCCUPIED',
    'spaces_available': 'SPACES AVAILABLE',
    'occupied_spots': 'Occupied Spots',
    'parking_info': 'Parking Information',
    'view_map': 'VIEW PARKING MAP',
    'reserved': 'Reserved',
    'maintenance': 'Maintenance',
    // Map Screen
    'parking_map': 'Parking Map',
    'floor': 'Floor',
    'spot': 'Spot #',
    'details': 'Details',
    'error': 'Error: ',
    'no_parking_data': 'No parking data available',
    'location': 'Location',
    'status': 'Status',
    'available_spots': 'Available Spots',
    'floor_1_not_available': 'Reservations are only available for Floor 2',
    // Profile Screen
    'my_profile': 'My Profile',
    'member_since': 'Member Since',
    'total_bookings': 'Total Bookings',
    'favorite_spots': 'Favorite Spots',
    'settings': 'Settings',
    'help_support': 'Help & Support',
    'about_us': 'About Us',
    'privacy_policy': 'Privacy Policy',
    'terms_conditions': 'Terms & Conditions',
    'logout': 'Logout',
    'no_profile_image': 'No Profile Image',
    // Stats Screen
    'statistics': 'Statistics',
    'parking_trends': 'Parking Trends',
    'weekly_summary': 'Weekly Summary',
    'average_occupancy': 'Average Occupancy',
    'total_spaces': 'Total Spaces',
    'empty_spaces': 'Empty Spaces',
    'busy': 'Busy',
    'quiet': 'Quiet',
    'moderate': 'Moderate',
    // Notifications Screen
    'notifications_title': 'Notifications',
    'no_notifications': 'No notifications',
    'notification_empty_title': 'No notifications',
    'notification_empty_subtitle': 'You will receive notifications here',
    'spot_available': 'Spot Available',
    'booking_reminder': 'Booking Reminder',
    'new_feature': 'New Feature',
    'mark_as_read': 'Mark as read',
    'clear_all': 'Clear All',
    // Additional keys - only new keys for home screen features
    'parking_occupancy': 'Parking Occupancy',
    'floor_2_realtime': 'Floor 2 - Real Time Status',
    'live_update': 'Live Update - Real Time Data',
    'peak_hours_today': 'Peak Hours Today',
    'peak_hours_value': '9:00 AM - 11:00 AM',
    'high_activity': 'High parking activity expected',
    'parking_available': 'Available',
    'parking_open': 'Parking is open with spaces',
    'avg_stay': 'Avg. Stay',
    'stay_updated': 'Stay updated with parking spots',
    'account_type': 'Account Type',
    'premium_member': 'Premium Member',
    'your_account_info': 'Your account information',
    'select_floor': 'Select Floor',
    'floor_1': 'Floor 1',
    'floor_2': 'Floor 2',
    'places_available': 'places available',
    'updated': 'Updated',
    // Reservation Screen
    'spot_occupied': 'This spot is occupied',
    'reservation_confirmed': 'Reservation Confirmed!',
    'your_code': 'Your Reservation Code',
    'valid_5_minutes': '⏱️ Valid for 5 minutes',
    // Stats screen translations
    'occupancy_floor_2': 'Occupancy - Floor 2',
    'place': 'place',
    'places': 'places',
    'occupied_or_reserved': 'occupied/reserved',
    'reserved_short': 'Reserved',
    'etage_2': 'Floor 2',
    'total_spots': 'Total',
    'all_spots': 'Spots',
    // Auth validations - NEW KEYS ONLY
    'email_required': 'Email is required',
    'password_required': 'Password is required',
    'password_min_8': 'Password must be at least 8 characters',
    'passwords_not_match': 'Passwords do not match',
    'invalid_email': 'Please enter a valid email address',
    'valid_email_format': 'Enter a valid email format',
    'reset_password_msg': 'Enter your email address and we\'ll send you a link to reset your password',
    'please_enter_email': 'Please enter your email address',
    'an_error_occurred': 'An error occurred',
    'try_again': 'Please try again',
    'account_created_success': 'Account created successfully!',
    // Auth form labels - NEW KEYS ONLY
    'join_parkino_today': 'Join Parkino today',
    'sign_in_welcome': 'Welcome to Parkino',
    'sign_up_welcome': 'Create Your Account',
    'choose_username': 'Choose your username',
    'example_email': 'example@parkino.com',
    'phone_format': '+1 (555) 000-0000',
    // Profile fields - NEW KEYS ONLY
    'display_name': 'Display Name',
    'email_address': 'Email Address',
    'phone_number': 'Phone Number',
    'save_changes': 'Save Changes',
    'loading': 'Loading...',
    'active_reservation_exists': 'You already have an active reservation. Please wait for it to expire or cancel it before reserving another spot.',
    // Confirmation/Reservation - NEW KEYS ONLY
    'reservation_confirmed_title': 'Reservation Confirmed!',
    'reservation_details': 'Reservation Details',
    'your_qr_code': 'Your Access QR Code',
    'important': 'Important',
    'reservation_id': 'Reservation ID',
    'payment_accepted': 'Your payment has been accepted',
    'present_qr_code': 'Present this QR code at the entrance to access your spot',
    'back_home': 'Back to Home',
    // Payment - NEW KEYS ONLY
    'payment_title': 'Payment',
    'reservation_summary': 'Reservation Summary',
    'payment_info': 'Payment Information',
    'card_number': 'Card Number',
    'cardholder_name': 'Cardholder Name',
    'expiration_date': 'Expiration Date',
    'cvv': 'CVV',
    'payment_now': 'Pay Now',
    'test_cards': 'Test Cards',
    'payment_accepted_card': 'Accepted Payment: 4242424242424242',
    'payment_rejected_card': 'Rejected Payment: 4000000000000000',
    'other_valid': 'Others: Accepted if valid',
    // Profile months - NEW KEYS
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    // User Management - NEW KEYS ONLY
    'no_user_logged_in': 'No user logged in',
    'current_user': 'Current User',
    'email_label': 'Email',
    'username_label': 'Username',
    'uid_label': 'UID',
    'email_verified': 'Email Verified',
    'yes': 'Yes',
    'no': 'No',
    'delete_floor_2': 'Delete Floor 2 (Admin)',
    'delete_confirm': 'DELETE COMPLETELY',
    'delete_warning': 'Warning message for deletion',
    'floor_2_deleted': 'All Floor 2 data has been deleted',
    'delete_error': 'Error during deletion',
    // Reservation Management - NEW KEYS ONLY
    'my_reservations': 'My Reservations',
    'no_reservations': 'No Reservations',
    'qr_access_code': 'Access QR Code',
    'floor_label': 'Floor',
    'duration_label': 'Duration',
    'amount_label': 'Amount',
    'status_label': 'Status',
    'date_time_label': 'Date/Time',
    'expires_in': 'Expires In',
    'id_label': 'ID',
    'spot_label': 'Spot',
    'please_sign_in': 'Please sign in',
    'make_reservation': 'Make a Reservation',
    'pending_payment': 'Pending Payment',
    'used': 'Used',
    'expired': 'Expired',
    'qr_instructions': 'QR code for access. Present it at the entrance',
    'qr_expired_msg': 'QR code expired',
    'qr_load_error': 'Error loading QR code',
    // Hub/Management - NEW KEYS ONLY
    'parkino_title': 'Parkino - Reservation',
    'reset_spots': 'Reset Spots',
    'reset_all': 'DELETE ALL',
    'reset_confirmation': 'Warning reset text',
    'my_reservations_btn': 'My Reservations',
    'validate_qr': 'Validate QR Code',
    'view_active': 'View my active reservations',
    'scan_qr': 'Scan or paste a QR code',
    'actions': 'Actions',
    'information': 'Information',
    'floor_2_closed': 'Floor 2: PERMANENTLY CLOSED',
    'floor_2_unavailable': 'Floor 2 is no longer available',
    'reset_success': 'Spots reset successfully',
    'data_deleted': 'All Floor 2 data has been deleted',
    // Notifications and Reservations
    'active_reservation': 'Active Reservation',
    'spot_number': 'Spot №',
    'you_have_reserved': 'You have reserved spot №',
    'reservation_error_title': 'Reservation Error',
    'reservation_error_message': 'The reservation could not be completed:',
    'reserved_status': 'RESERVED',
    // Generic translations
    'code': 'Code',
  };

  // French translations
  static const Map<String, String> _fr = {
    'app_name': 'Parkino',
    'sign_in': 'Se connecter',
    'sign_up': 'S\'inscrire',
    'create_account': 'Créer un compte',
    'forgot_password': 'Mot de passe oublié?',
    'remember_me': 'Se souvenir de moi',
    'password': 'Mot de passe',
    'email': 'Adresse e-mail',
    'email_hint': 'vous@exemple.com',
    'password_hint': 'Entrez votre mot de passe',
    'username': 'Nom d\'utilisateur',
    'phone': 'Numéro de téléphone',
    'confirm_password': 'Confirmer le mot de passe',
    'create_an_account': 'Créer votre compte',
    'sign_in_title': 'Heureux de vous revoir',
    'dont_have_account': "Vous n'avez pas de compte? ",
    'already_have_account': 'Vous avez déjà un compte? ',
    'home': 'Accueil',
    'map': 'Carte',
    'stats': 'Statistiques',
    'notifications': 'Notifications',
    'profile': 'Profil',
    'parking_availability': 'Disponibilité du stationnement',
    'current_status': 'État actuel',
    'available': 'DISPONIBLE',
    'full': 'COMPLET',
    'occupied': 'OCCUPÉ',
    'free': 'LIBRE',
    'peak_hours': 'Heures de pointe',
    'nearest_spot': 'Place la plus proche',
    'view_parking_map': 'VOIR LA CARTE DE STATIONNEMENT',
    'language': 'Langue',
    'english': 'English',
    'french': 'Français',
    'arabic': 'العربية',
    // User management
    'user_management': 'Gestion des utilisateurs',
    'back_to_sign_in': 'Retour à la connexion',
    'go_to_home': 'Aller à l\'accueil',
    'sign_out': 'Se déconnecter',
    'are_you_sure_sign_out': 'Êtes-vous sûr de vouloir vous déconnecter?',
    'cancel': 'Annuler',
    'reset_password': 'Réinitialiser le mot de passe',
    'send_reset_link': 'Envoyer le lien de réinitialisation',
    'password_reset_successful': 'Mot de passe réinitialisé avec succès!',
    'welcome_to_parkino': 'Bienvenue à Parkino',
    'sign_in_successful': 'Connexion réussie!',
    'sign_in_failed': 'Échec de la connexion',
    'create_account_button': 'Créer un compte',
    'go_to_sign_in': 'Aller à la connexion',
    'edit_profile': 'Modifier le profil',
    'close': 'Fermer',
    'coming_soon': 'Bientôt disponible',
    // Home Screen
    'smart_parking': 'Stationnement Intelligent',
    'parking_status': 'État du Stationnement',
    'fully_occupied': 'ENTIÈREMENT OCCUPÉ',
    'spaces_available': 'PLACES DISPONIBLES',
    'occupied_spots': 'Places Occupées',
    'parking_info': 'Informations de Stationnement',
    'view_map': 'VOIR LA CARTE DE STATIONNEMENT',
    'reserved': 'Réservé',
    'maintenance': 'Maintenance',
    // Map Screen
    'parking_map': 'Carte de Stationnement',
    'floor': 'Étage',
    'spot': 'Place n°',
    'details': 'Détails',
    'error': 'Erreur: ',
    'no_parking_data': 'Aucune donnée de stationnement disponible',
    'location': 'Localisation',
    'status': 'Statut',
    'available_spots': 'Places Disponibles',
    'floor_1_not_available': 'Les réservations ne sont disponibles que pour l\'Étage 2',
    // Profile Screen
    'my_profile': 'Mon Profil',
    'member_since': 'Membre depuis',
    'total_bookings': 'Total des Réservations',
    'favorite_spots': 'Places Favorites',
    'settings': 'Paramètres',
    'help_support': 'Aide & Support',
    'about_us': 'À Propos de Nous',
    'privacy_policy': 'Politique de Confidentialité',
    'terms_conditions': 'Conditions & Termes',
    'logout': 'Déconnexion',
    'no_profile_image': 'Pas d\'image de profil',
    // Stats Screen
    'statistics': 'Statistiques',
    'parking_trends': 'Tendances de Stationnement',
    'weekly_summary': 'Résumé Hebdomadaire',
    'average_occupancy': 'Occupation Moyenne',
    'total_spaces': 'Total des Places',
    'empty_spaces': 'Places Vides',
    'busy': 'Occupé',
    'quiet': 'Calme',
    'moderate': 'Modéré',
    // Notifications Screen
    'notifications_title': 'Notifications',
    'no_notifications': 'Aucune notification',    'notification_empty_title': 'Pas de notifications',
    'notification_empty_subtitle': 'Vous recevrez les notifications ici',    'spot_available': 'Place Disponible',
    'booking_reminder': 'Rappel de Réservation',
    'new_feature': 'Nouvelle Fonctionnalité',
    'mark_as_read': 'Marquer comme lu',
    'clear_all': 'Tout Effacer',
    // Additional keys - only new keys for home screen features
    'parking_occupancy': 'Occupation du Stationnement',
    'floor_2_realtime': 'Étage 2 - État en Temps Réel',
    'live_update': 'Mise à jour en Direct - Données en Temps Réel',
    'peak_hours_today': 'Heures de Pointe Aujourd\'hui',
    'peak_hours_value': '9:00 AM - 11:00 AM',
    'high_activity': 'Activité de stationnement élevée attendue',
    'parking_available': 'Disponible',
    'parking_open': 'Le stationnement est ouvert avec des places',

    'avg_stay': 'Durée moy.',
    'stay_updated': 'Restez à jour avec les places de stationnement',
    'account_type': 'Type de compte',
    'premium_member': 'Membre Premium',
    'your_account_info': 'Votre information de compte',
    'select_floor': 'Sélectionner étage',
    'floor_1': 'Étage 1',
    'floor_2': 'Étage 2',
    'places_available': 'places disponibles',
    'updated': 'Mis à jour',    // Reservation Screen
    'spot_occupied': 'Cette place est occupée',
    'your_reservation': 'Votre réservation',
    'reserved_spot': 'Place réservée',
    'already_reserved': 'Vous avez déjà réservé cette place',
    'reserved_by_other': 'Cette place est réservée par quelqu\'un d\'autre',
    'reservation_confirmed': 'Réservation Confirmée!',
    'your_code': 'Votre Code de Réservation',
    'valid_5_minutes': '⏱️ Valide pour 5 minutes',
    // Stats screen translations
    'occupancy_floor_2': 'Occupation - Étage 2',
    'place': 'place',
    'places': 'places',
    'occupied_or_reserved': 'occupée(s)/réservée(s)',
    'reserved_short': 'Réservées',
    'etage_2': 'Étage 2',
    'total_spots': 'Total',
    'all_spots': 'Places',
    // Auth validations - NEW KEYS ONLY
    'email_required': 'Email est requis',
    'password_required': 'Le mot de passe est requis',
    'password_min_8': 'Le mot de passe doit contenir au moins 8 caractères',
    'passwords_not_match': 'Les mots de passe ne correspondent pas',
    'invalid_email': 'Veuillez entrer une adresse email valide',
    'valid_email_format': 'Entrez un format d\'email valide',
    'reset_password_msg': 'Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe',
    'please_enter_email': 'Veuillez entrer votre adresse email',
    'an_error_occurred': 'Une erreur s\'est produite',
    'try_again': 'Veuillez réessayer',
    'account_created_success': 'Compte créé avec succès!',
    // Auth form labels - NEW KEYS ONLY
    'join_parkino_today': 'Rejoignez Parkino aujourd\'hui',
    'sign_in_welcome': 'Bienvenue à Parkino',
    'sign_up_welcome': 'Créer votre compte',
    'choose_username': 'Choisissez votre nom d\'utilisateur',
    'example_email': 'exemple@parkino.com',
    'phone_format': '+33 (0) 1 23 45 67 89',
    // Profile fields - NEW KEYS ONLY
    'display_name': 'Nom d\'affichage',
    'email_address': 'Adresse email',
    'phone_number': 'Numéro de téléphone',
    'save_changes': 'Enregistrer les modifications',
    'loading': 'Chargement...',
    'active_reservation_exists': 'Vous avez déjà une réservation active. Veuillez attendre son expiration ou l\'annuler avant de réserver une autre place.',
    // Confirmation/Reservation - NEW KEYS ONLY
    'reservation_confirmed_title': 'Réservation confirmée!',
    'reservation_details': 'Détails de la réservation',
    'your_qr_code': 'Votre code QR d\'accès',
    'important': 'Important',
    'reservation_id': 'Identifiant de réservation',
    'payment_accepted': 'Votre paiement a été accepté',
    'present_qr_code': 'Présentez ce code QR à l\'entrée pour accéder à votre place',
    'back_home': 'Retour à l\'accueil',
    // Payment - NEW KEYS ONLY
    'payment_title': 'Payment',
    'reservation_summary': 'Reservation Summary',
    'payment_info': 'Payment Information',
    'card_number': 'Card Number',
    'cardholder_name': 'Cardholder Name',
    'expiration_date': 'Expiration Date',
    'cvv': 'CVV',
    'payment_now': 'Pay Now',
    'test_cards': 'Test Cards',
    'payment_accepted_card': 'Accepted Payment: 4242424242424242',
    'payment_rejected_card': 'Rejected Payment: 4000000000000000',
    'other_valid': 'Others: Accepted if valid',
    // Profile months - NEW KEYS
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    // User Management - NEW KEYS ONLY
    'no_user_logged_in': 'No user logged in',
    'current_user': 'Current User',
    'email_label': 'Email',
    'username_label': 'Username',
    'uid_label': 'UID',
    'email_verified': 'Email Verified',
    'yes': 'Yes',
    'no': 'No',
    'delete_floor_2': 'Delete Floor 2 (Admin)',
    'delete_confirm': 'DELETE COMPLETELY',
    'delete_warning': 'Warning message for deletion',
    'floor_2_deleted': 'All Floor 2 data has been deleted',
    'delete_error': 'Error during deletion',
    // Reservation Management - NEW KEYS ONLY
    'my_reservations': 'My Reservations',
    'no_reservations': 'No Reservations',
    'qr_access_code': 'Access QR Code',
    'floor_label': 'Floor',
    'duration_label': 'Duration',
    'amount_label': 'Amount',
    'status_label': 'Status',
    'date_time_label': 'Date/Time',
    'expires_in': 'Expires In',
    'id_label': 'ID',
    'spot_label': 'Spot',
    'please_sign_in': 'Please sign in',
    'make_reservation': 'Make a Reservation',
    'pending_payment': 'Pending Payment',
    'used': 'Used',
    'expired': 'Expired',
    'qr_instructions': 'QR code for access. Present it at the entrance',
    'qr_expired_msg': 'QR code expired',
    'qr_load_error': 'Error loading QR code',
    // Hub/Management - NEW KEYS ONLY
    'parkino_title': 'Parkino - Reservation',
    'reset_spots': 'Reset Spots',
    'reset_all': 'DELETE ALL',
    'reset_confirmation': 'Warning reset text',
    'my_reservations_btn': 'My Reservations',
    'validate_qr': 'Validate QR Code',
    'view_active': 'View my active reservations',
    'scan_qr': 'Scan or paste a QR code',
    'actions': 'Actions',
    'information': 'Informations',
    'floor_2_closed': 'Étage 2: FERMÉ DÉFINITIVEMENT',
    'floor_2_unavailable': 'L\'étage 2 n\'est plus disponible',
    'reset_success': 'Places réinitialisées avec succès',
    'data_deleted': 'Toutes les données d\'Étage 2 ont été supprimées',
    // Notifications and Reservations
    'active_reservation': 'Réservation active',
    'spot_number': 'Place n°',
    'you_have_reserved': 'Vous avez réservé la place n°',
    'reservation_error_title': 'Erreur de réservation',
    'reservation_error_message': 'La réservation n\'a pas pu être complétée:',
    'reserved_status': 'RÉSERVÉE',
    // Generic translations
    'code': 'Code',
  };

  // Arabic translations
  static const Map<String, String> _ar = {
    'app_name': 'باركينو',
    'sign_in': 'تسجيل الدخول',
    'sign_up': 'إنشاء حساب',
    'create_account': 'إنشاء حساب',
    'forgot_password': 'هل نسيت كلمة المرور؟',
    'remember_me': 'تذكرني',
    'password': 'كلمة المرور',
    'email': 'عنوان البريد الإلكتروني',
    'email_hint': 'you@example.com',
    'password_hint': 'أدخل كلمة المرور الخاصة بك',
    'username': 'اسم المستخدم',
    'phone': 'رقم الهاتف',
    'confirm_password': 'تأكيد كلمة المرور',
    'create_an_account': 'إنشاء حسابك',
    'sign_in_title': 'أهلا وسهلا',
    'dont_have_account': 'ليس لديك حساب؟ ',
    'already_have_account': 'هل لديك حساب بالفعل؟ ',
    'home': 'الرئيسية',
    'map': 'الخريطة',
    'stats': 'الإحصائيات',
    'notifications': 'الإخطارات',
    'profile': 'الملف الشخصي',
    'parking_availability': 'توفر مواقف السيارات',
    'current_status': 'الحالة الحالية',
    'available': 'متاح',
    'full': 'ممتلئ',
    'occupied': 'مشغول',
    'free': 'حر',
    'peak_hours': 'ساعات الذروة',
    'nearest_spot': 'أقرب مكان',
    'view_parking_map': 'عرض خريطة المواقف',
    'language': 'اللغة',
    'english': 'English',
    'french': 'Français',
    'arabic': 'العربية',
    // User management
    'user_management': 'إدارة المستخدمين',
    'back_to_sign_in': 'العودة إلى تسجيل الدخول',
    'go_to_home': 'انتقل إلى الرئيسية',
    'sign_out': 'تسجيل الخروج',
    'are_you_sure_sign_out': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
    'cancel': 'إلغاء',
    'reset_password': 'إعادة تعيين كلمة المرور',
    'send_reset_link': 'إرسال رابط إعادة التعيين',
    'password_reset_successful': 'تم إعادة تعيين كلمة المرور بنجاح!',

    'welcome_to_parkino': 'أهلا بك في باركينو',
    'sign_in_successful': 'تم تسجيل الدخول بنجاح!',
    'sign_in_failed': 'فشل تسجيل الدخول',
    'create_account_button': 'إنشاء حساب',
    'go_to_sign_in': 'انتقل إلى تسجيل الدخول',
    'edit_profile': 'تعديل الملف الشخصي',
    'close': 'إغلاق',
    'coming_soon': 'قريبا',
    // Home Screen
    'smart_parking': 'مواقف ذكية',
    'parking_status': 'حالة مواقف السيارات',
    'fully_occupied': 'ممتلئ تماما',
    'spaces_available': 'مساحات متاحة',
    'occupied_spots': 'المساحات المشغولة',
    'parking_info': 'معلومات مواقف السيارات',
    'view_map': 'عرض خريطة المواقف',
    'reserved': 'محجوز',
    'maintenance': 'صيانة',
    // Map Screen
    'parking_map': 'خريطة مواقف السيارات',
    'floor': 'الطابق',
    'spot': 'موقف رقم',
    'details': 'التفاصيل',
    'error': 'خطأ: ',
    'no_parking_data': 'لا توجد بيانات موقف متاحة',
    'location': 'الموقع',
    'status': 'الحالة',
    'available_spots': 'المساحات المتاحة',
    'floor_1_not_available': 'الحجوزات متاحة فقط للطابق 2',
    // Profile Screen
    'my_profile': 'ملفي الشخصي',
    'member_since': 'عضو منذ',
    'total_bookings': 'إجمالي الحجوزات',
    'favorite_spots': 'المواقف المفضلة',
    'settings': 'الإعدادات',
    'help_support': 'المساعدة والدعم',
    'about_us': 'عن ننا',
    'privacy_policy': 'سياسة الخصوصية',
    'terms_conditions': 'الشروط والشروط',
    'logout': 'تسجيل الخروج',
    'no_profile_image': 'لا توجد صورة ملف شخصي',
    // Stats Screen
    'statistics': 'الإحصائيات',
    'parking_trends': 'اتجاهات المواقف',
    'weekly_summary': 'الملخص الأسبوعي',
    'average_occupancy': 'متوسط الاحتلال',
    'total_spaces': 'إجمالي المساحات',
    'empty_spaces': 'مساحات فارغة',
    'busy': 'مشغول',
    'quiet': 'هادئ',
    'moderate': 'معتدل',
    // Notifications Screen
    'notifications_title': 'الإخطارات',
    'no_notifications': 'لا توجد إخطارات',    'notification_empty_title': 'لا توجد إخطارات',
    'notification_empty_subtitle': 'ستتلقى الإخطارات هنا',    'spot_available': 'موقف متاح',
    'booking_reminder': 'تذكير الحجز',
    'new_feature': 'ميزة جديدة',
    'mark_as_read': 'وضع العلامة كمقروء',
    'clear_all': 'مسح الكل',
    // Additional keys - only new keys for home screen features
    'parking_occupancy': 'شغل المواقف',
    'floor_2_realtime': 'الطابق 2 - حالة فورية',
    'live_update': 'تحديث مباشر - بيانات فورية',
    'peak_hours_today': 'ساعات الذروة اليوم',
    'peak_hours_value': '9:00 AM - 11:00 AM',
    'high_activity': 'نشاط موقف عالي متوقع',
    'parking_available': 'متاح',
    'parking_open': 'المواقف مفتوحة مع مساحات',
    'avg_stay': 'متوسط الإقامة',
    'stay_updated': 'ابق على اطلاع على مواقف السيارات',
    'account_type': 'نوع الحساب',
    'premium_member': 'عضو ممتاز',
    'your_account_info': 'معلومات حسابك',
    'select_floor': 'اختر الطابق',
    'floor_1': 'الطابق 1',
    'floor_2': 'الطابق 2',
    'places_available': 'مواقف متاحة',
    'updated': 'تم التحديث',
    // Reservation Screen
    'spot_occupied': 'هذا الموقف محتل',
    'your_reservation': 'حجزك',
    'reserved_spot': 'موقف محجوز',
    'already_reserved': 'لقد حجزت بالفعل هذا الموقف',
    'reserved_by_other': 'هذا الموقف محجوز من قبل شخص آخر',
    'reservation_confirmed': 'تم تأكيد الحجز!',
    'your_code': 'رمز الحجز الخاص بك',
    'valid_5_minutes': '⏱️ صالح لمدة 5 دقائق',
    // Stats screen translations
    'occupancy_floor_2': 'الاحتلال - الطابق 2',
    'place': 'موقف',
    'places': 'مواقف',
    'occupied_or_reserved': 'مشغول/محجوز',
    'reserved_short': 'محجوزة',
    'etage_2': 'الطابق 2',
    'total_spots': 'الإجمالي',
    'all_spots': 'المواقف',

    // Auth validations - NEW KEYS ONLY
    'email_required': 'البريد الإلكتروني مطلوب',
    'password_required': 'كلمة المرور مطلوبة',
    'password_min_8': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    'passwords_not_match': 'كلمات المرور لا تتطابق',
    'invalid_email': 'يرجى إدخال عنوان بريد إلكتروني صحيح',
    'valid_email_format': 'أدخل تنسيق بريد إلكتروني صحيح',
    'reset_password_msg': 'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور الخاصة بك',
    'please_enter_email': 'يرجى إدخال عنوان بريدك الإلكتروني',
    'an_error_occurred': 'حدث خطأ',
    'try_again': 'يرجى المحاولة مرة أخرى',
    'account_created_success': 'تم إنشاء الحساب بنجاح!',
    // Auth form labels - NEW KEYS ONLY
    'join_parkino_today': 'انضم إلى باركينو اليوم',
    'sign_in_welcome': 'أهلا بك في باركينو',
    'sign_up_welcome': 'أنشئ حسابك',
    'choose_username': 'اختر اسم المستخدم الخاص بك',
    'example_email': 'مثال@parkino.com',
    'phone_format': '+966 50 123 4567',
    // Profile fields - NEW KEYS ONLY
    'display_name': 'اسم العرض',
    'email_address': 'عنوان البريد الإلكتروني',
    'phone_number': 'رقم الهاتف',
    'save_changes': 'حفظ التغييرات',
    'loading': 'جاري التحميل...',
    // Confirmation/Reservation - NEW KEYS ONLY
    'reservation_confirmed_title': 'تم تأكيد الحجز!',
    'reservation_details': 'تفاصيل الحجز',
    'your_qr_code': 'كود QR للوصول الخاص بك',
    'important': 'مهم',
    'reservation_id': 'معرف الحجز',
    'payment_accepted': 'تم قبول دفعتك',
    'present_qr_code': 'قدّم رمز QR هذا عند المدخل للوصول إلى موقفك',
    'back_home': 'العودة إلى الرئيسية',
    // Payment - NEW KEYS ONLY
    'payment_title': 'الدفع',
    'reservation_summary': 'ملخص الحجز',
    'payment_info': 'معلومات الدفع',
    'card_number': 'رقم البطاقة',
    'cardholder_name': 'اسم صاحب البطاقة',
    'expiration_date': 'تاريخ الانتهاء',
    'cvv': 'CVV',
    'payment_now': 'ادفع الآن',
    'test_cards': 'بطاقات اختبار',
    'payment_accepted_card': 'الدفع المقبول: 4242424242424242',
    'payment_rejected_card': 'الدفع المرفوض: 4000000000000000',
    'other_valid': 'آخرى: مقبول إذا كان صحيحًا',
    // Profile months - NEW KEYS
    'january': 'يناير',
    'february': 'فبراير',
    'march': 'مارس',
    'april': 'أبريل',
    'may': 'مايو',
    'june': 'يونيو',
    'july': 'يوليو',
    'august': 'أغسطس',
    'september': 'سبتمبر',
    'october': 'أكتوبر',
    'november': 'نوفمبر',
    'december': 'ديسمبر',
    // User Management - NEW KEYS ONLY
    'no_user_logged_in': 'لا يوجد مستخدم مسجل دخول',
    'current_user': 'المستخدم الحالي',
    'email_label': 'البريد الإلكتروني',
    'username_label': 'اسم المستخدم',
    'uid_label': 'UID',
    'email_verified': 'تم التحقق من البريد الإلكتروني',
    'yes': 'نعم',
    'no': 'لا',
    'delete_floor_2': 'حذف الطابق 2 (المسؤول)',
    'delete_confirm': 'حذف تماما',
    'delete_warning': 'رسالة تحذير للحذف',
    'floor_2_deleted': 'تم حذف جميع بيانات الطابق 2',
    'delete_error': 'خطأ أثناء الحذف',
    // Reservation Management - NEW KEYS ONLY
    'my_reservations': 'حجوزاتي',
    'no_reservations': 'لا توجد حجوزات',
    'qr_access_code': 'كود وصول QR',
    'floor_label': 'الطابق',
    'duration_label': 'المدة',
    'amount_label': 'المبلغ',
    'status_label': 'الحالة',
    'date_time_label': 'التاريخ/الوقت',
    'expires_in': 'ينتهي في',
    'id_label': 'معرف',
    'spot_label': 'موقف',
    'please_sign_in': 'يرجى تسجيل الدخول',
    'make_reservation': 'قم بحجز',
    'pending_payment': 'الدفع قيد الانتظار',
    'used': 'مستخدم',
    'expired': 'منتهي الصلاحية',
    'qr_instructions': 'رمز QR للوصول. قدّمه عند المدخل',
    'qr_expired_msg': 'رمز QR منتهي الصلاحية',
    'qr_load_error': 'خطأ في تحميل رمز QR',
    // Notifications and Reservations
    'active_reservation': 'حجز نشط',
    'spot_number': 'المكان رقم',
    'you_have_reserved': 'لقد حجزت المكان رقم',
    'reservation_error_title': 'خطأ في الحجز',
    'reservation_error_message': 'لم يتمكن من إكمال الحجز:',
    'reserved_status': 'محجوزة',
    // Generic translations
    'code': 'الرمز',
    // Hub/Management - NEW KEYS ONLY

  };

  /// Get current locale
  static String get currentLocale => _currentLocale;

  /// Set current locale
  static void setLocale(String locale) {
    if (['en', 'fr', 'ar'].contains(locale)) {
      _currentLocale = locale;
    }
  }

  /// Get localized string by key
  static String translate(String key) {
    final Map<String, String> currentMap;
    
    switch (_currentLocale) {
      case 'fr':
        currentMap = _fr;
        break;
      case 'ar':
        currentMap = _ar;
        break;
      default:
        currentMap = _en;
    }
    
    return currentMap[key] ?? key;
  }

  /// Alias for translate method
  static String t(String key) => translate(key);
}
